trigger:
  branches:
    include:
    - Assignment-2

pool:
  vmImage: 'ubuntu-latest'


variables:
  azureSubscription: 'SC-UDST-CCIT-DSAI3202'
  resourceGroup: 'rg-60306249'
  workspace: 'Amazon-lab2-60306249'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: |
    pip install azure-cli
    az extension add -n ml
  displayName: 'Install Azure CLI'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az configure --defaults group=$(resourceGroup) workspace=$(workspace)
      az ml job create --file jobs/train_job.yml
  displayName: 'Submit Training Job to Azure ML'